### ISSUE TITLE
support multi-flavor configrations

### ISSUE THREAD

**Issue by ghost** [quux00/mybatis-koans#10]
currently 

config.properties

```
# TODO: set up the correct JDBC database driver and url

#####################################################

# PostgreSQL version
#driver=org.postgresql.Driver
#url=jdbc:postgresql:sakila

# TODO: fill in your username and password
#username=midpeter444
#password=jiffylube

#####################################################

# MySQL version
# driver=com.mysql.jdbc.Driver
# url=jdbc:mysql://localhost:3306/sakila

# TODO: fill in your username and password
#username=midpeter444
#password=jiffylube

#####################################################

# H2 version

driver=org.h2.Driver
url=jdbc:h2:tcp://localhost/sakila

username=sa
password=
```

must be manually edited per each db flavor;

the idea is to provide easy default settings for each flavor with
- host = localhost
- user = sa
- pass is blank

which could be reasonable for local test-only user database

**Comment by quux00** [comment]
Hi Andrei,

If we create multiple config.properties files, one for each database, how
are we going to specify which config files should be used in each
koan-config.xml?  Would we have to create a -pg, -mysql and -h2 version of
each koan?  If so, I don't like that idea.  Let me know if you have a good
way to do this.

If not, I think automating H2 and making that the default to run out of the
box is the best choice.  The other dbs can be set up by the user as s/he
chooses.

Again feel free to give a different point of view if I'm not seeing how are
planning to do it.

-Michael

On Fri, Jul 13, 2012 at 10:11 AM, Andrei Pozolotin <
reply@reply.github.com

**Comment by ghost** [comment]
please take a look:

https://github.com/carrot-garden/sql_mybatis-koans/commit/d3e2604eacc4b2d46f59f464d6590e85fd879d15
