### ISSUE TITLE
Write pom targets to run koans from maven

### ISSUE THREAD

**Issue by quux00** [quux00/mybatis-koans#4]
A user should be able to run these from the command line or within Eclipse (using m2e?)

In particular, a user should be able to run:
- All completed koans in src/test in one command
- Any individual koan in src/test with a single command targeting that koan (such as `mvn test --activate-profile koan11`)
- All koans in src/main that the user has completed
- Any individual koan in src/main that the user is working on with a single command targeting that koan (such as `mvn run --activate-profile koan11`)

**Comment by ghost** [comment]
basic approach shown in 

/sql_mybatis-koans/build/maven-run-test-koan02-h2.ant

such as

mvn clean verify -P run-test-koans-h2 -D koanName=Koan02

please review
