### ISSUE TITLE
Get stored proc koans working with H2

### ISSUE THREAD

**Issue by quux00** [quux00/mybatis-koans#5]
Koans 16 and 17 use stored funcs/stored procs.  Can these koans be made to work with H2?  Build working Koans for these or document in the README.md that this can't be done.

**Comment by ghost** [comment]
stored funcs/stored procs almost works

https://github.com/carrot-garden/sql_mybatis-koans/tree/master/src/test/java/net/thornydev/mybatis/test/koan16/h2

pending this

http://stackoverflow.com/questions/11417133/how-to-specify-java-class-version-for-h2-database-user-defined-functions-and-sto

**Comment by ghost** [comment]
please review

/sql_mybatis-koans/src/test/java/net/thornydev/mybatis/test/koan16/h2

/sql_mybatis-koans/src/test/java/net/thornydev/mybatis/test/koan17/h2
