### ISSUE TITLE
turn off logging output by default when run ant targets

### ISSUE THREAD

**Issue by quux00** [quux00/mybatis-koans#8]
When running ant koans from the command line, the logging output is too much line noise - need to turn logging off by default for ant, but allow switch to turn it back on.  Had a way to do this in the earlier version, so need to do this for the new version with the new logging system.

**Comment by ghost** [comment]
please review

/sql_mybatis-koans/src/test/resources/logback-test.xml

**Comment by quux00** [comment]
Hi Andrei,

Thanks for this.  I got it pulled in to the ant builds now and checked that
into your repo.

-Michael

On Fri, Jul 13, 2012 at 9:14 AM, Andrei Pozolotin <
reply@reply.github.com
